### ISSUE TITLE
NPE when using json created from (final File file) constructor

### ISSUE THREAD

**Issue by OfficialDonut** [JavaFactoryDev/LightningStorage#5]
**Describe the bug**
An NPE is thrown when you try to use a json created from the (final File file) constructor. This does not happen when using a different constructor. I also tested the (final File file) constructor with yaml and that does work

**To Reproduce**
```
Json json = new Json(new File("C:\\some\\path\\test.json"));
json.set("test", 1);
```
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.NullPointerException
	at de.leonhard.storage.Json.reload(Json.java:156)
	at de.leonhard.storage.Json.set(Json.java:444)
```

**Comment by JavaFactoryDev** [comment]
Hi, thank you for using LightningStorage & your help to improve it!
We have fixed this bug. Please update to 2.4
Issues will be processed more quickly in the future. 
Notifications were disabled.

Greetings,
Leonhard | EsGibtKeineMitte | JavaFactory
